name: CD Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths-ignore:
      - '**/*.md'

env:
  DOCKERHUB_USERNAME: dimitri134
  KUBERNETES_NAMESPACE: m324-1
  APP_NAME: modul324-ab05-dimitri
  IMAGE_TAG: dimitri134/m324-simple-typescript:${{ github.sha }}
  BASE_URL: dimitri.m324.hackerman.ch

  



jobs:
  docker:
    runs-on: self-hosted
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DIMITRI }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DIMITRI }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}
      
      - name: Check and Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/00_namespace.yml
            .k8s/01_deployment.yml
            .k8s/02_service.yml
            .k8s/03_ingress.yml
          replacement-method: defined

     

      

