name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  docker:
    runs-on: self-hosted
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DIMITRI }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DIMITRI }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dimitri134/m324-simple-typescript:latest

