name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - opened
jobs:
  docker:
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: dimitri134/m324-simple-typescript:latest

